import {Shipment, ShipmentStatus} from './types';

export const shipmentHistory: Shipment[] = [
  {
    shippingId: 'SHIP001',
    destination: {city: 'Cairo', address: '123 Tahrir Square'},
    origin: {city: 'Alexandria', address: '456 Corniche Road'},
    phoneNo: '010-1234-5678',
    status: 'delivered',
  },
  {
    shippingId: 'SHIP002',
    destination: {city: 'Giza', address: '789 Pyramids Street'},
    origin: {city: 'Luxor', address: '101 Nile Avenue'},
    phoneNo: '011-2345-6789',
    status: 'received',
  },
  {
    shippingId: 'SHIP003',
    destination: {city: 'Cairo', address: '123 Tahrir Square'},
    origin: {city: 'Aswan', address: '303 High Dam Road'},
    phoneNo: '012-3456-7890',
    status: 'on hold',
  },
  {
    shippingId: 'SHIP004',
    destination: {city: 'Hurghada', address: '404 Marina Boulevard'},
    origin: {city: 'Ismailia', address: '505 Suez Canal Street'},
    phoneNo: '013-4567-8901',
    status: 'canceled',
  },
  {
    shippingId: 'SHIP005',
    destination: {city: 'Suez', address: '606 Port Tawfiq Street'},
    origin: {city: 'Port Said', address: '707 Martyrs Street'},
    phoneNo: '014-5678-9012',
    status: 'error',
  },
  {
    shippingId: 'SHIP006',
    destination: {city: 'Mansoura', address: '808 El Gomhoria Street'},
    origin: {city: 'Zagazig', address: '909 Tanta Street'},
    phoneNo: '015-6789-0123',
    status: 'delivered',
  },
  {
    shippingId: 'SHIP007',
    destination: {city: 'Fayoum', address: '1010 Saad Zaghloul Street'},
    origin: {city: 'Beni Suef', address: '1111 El Horreya Road'},
    phoneNo: '016-7890-1234',
    status: 'received',
  },
  {
    shippingId: 'SHIP008',
    destination: {city: 'Minya', address: '1212 26th of July Street'},
    origin: {city: 'Assiut', address: '1313 Nasser Road'},
    phoneNo: '017-8901-2345',
    status: 'on hold',
  },
  {
    shippingId: 'SHIP009',
    destination: {city: 'Qena', address: '1414 Ahmed Orabi Street'},
    origin: {city: 'Sohag', address: '1515 Gamal Abdel Nasser Road'},
    phoneNo: '018-9012-3456',
    status: 'canceled',
  },
  {
    shippingId: 'SHIP010',
    destination: {city: 'Damietta', address: '1616 El Corniche Street'},
    origin: {city: 'Kafr El Sheikh', address: '1717 Sidi Salem Street'},
    phoneNo: '019-0123-4567',
    status: 'error',
  },
  {
    shippingId: 'SHIP011',
    destination: {city: 'Arish', address: '1818 El Salam Street'},
    origin: {city: 'Banha', address: '1919 El Qawmeya Road'},
    phoneNo: '020-1234-5678',
    status: 'delivered',
  },
  {
    shippingId: 'SHIP012',
    destination: {city: 'Damanhur', address: '2020 Al Azhar Street'},
    origin: {city: 'Tanta', address: '2121 Mahalet Rouh Street'},
    phoneNo: '021-2345-6789',
    status: 'received',
  },
  {
    shippingId: 'SHIP013',
    destination: {city: 'Banha', address: '2222 El Nasr Road'},
    origin: {city: 'Beni Suef', address: '2323 El Obour Street'},
    phoneNo: '022-3456-7890',
    status: 'on hold',
  },
  {
    shippingId: 'SHIP014',
    destination: {city: 'Sohag', address: '2424 El Gaish Street'},
    origin: {city: 'Ismailia', address: '2525 Abbas El Akkad Street'},
    phoneNo: '023-4567-8901',
    status: 'canceled',
  },
  {
    shippingId: 'SHIP015',
    destination: {city: 'Luxor', address: '2626 Luxor Temple Street'},
    origin: {city: 'Aswan', address: '2727 Philae Street'},
    phoneNo: '024-5678-9012',
    status: 'error',
  },
  {
    shippingId: 'SHIP016',
    destination: {city: 'Hurghada', address: '2828 Sheraton Road'},
    origin: {city: 'El Gouna', address: '1 Abu-Mena Street (near Abu Mena Christian complex)'},
    phoneNo: '025-6789-0123',
    status: 'delivered',
  },
  {
    shippingId: 'SHIP017',
    destination: {city: 'Alexandria', address: '3030 Stanley Bridge Road'},
    origin: {city: 'Cairo', address: '3131 Salah Salem Street'},
    phoneNo: '026-7890-1234',
    status: 'received',
  },
  {
    shippingId: 'SHIP018',
    destination: {city: 'Aswan', address: '3232 Nubia Museum Street'},
    origin: {city: 'Luxor', address: '3333 Karnak Temple Street'},
    phoneNo: '027-8901-2345',
    status: 'on hold',
  },
  {
    shippingId: 'SHIP019',
    destination: {city: 'Port Said', address: '3434 El Shaheed Atef El Sadat Street'},
    origin: {city: 'Ismailia', address: '3535 El Bahr Road'},
    phoneNo: '028-9012-3456',
    status: 'canceled',
  },
  {
    shippingId: 'SHIP020',
    destination: {city: 'Qena', address: '3636 Abdel Monem Riad Street'},
    origin: {city: 'Sohag', address: '3737 Kafr El Sheikh Street'},
    phoneNo: '029-0123-4567',
    status: 'error',
  },
];

export const shipmentStatusList = ['received', 'putaway', 'delivered', 'canceled', 'rejected', 'lost', 'on hold'] as ShipmentStatus[];
